server:
  port: 8085

spring:
  application:
    name: payment-service

  datasource:
    url: jdbc:mysql://localhost:3306/agrimarket_payment?createDatabaseIfNotExist=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
